server:
  port:
    redirector: 8080
    crud: 8081
    crud_http: 8082
  debug: true

mapper:
  persistor: boltdb
  mappers:
    - type: file
      name: file1
      path: ./files/maps.yaml
      syncInterval: 60
    # - type: file
    #   name: file2
    #   path: ./files/maps.json
    #   syncInterval: -1 # disable hot reload
    - type: mem
      name: memory
      pairs:
        - path: ggl
          url: https://google.com
        - path: me
          url: https://github.com/Reimirno/golinks
    - type: bolt
      name: boltdb
      path: maps.db
      timeout: 10
    # - type: sql
    #   name:
    #   driver:
    #   dsn:
