name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    name: Unit test with make
    strategy:
      matrix:
        go-version: ["1.22"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure
      uses: ./.github/actions/configure
      with:
        go-version: ${{ matrix.go-version }}
    - name: Gen proto
      run: make gen
    - name: Unit test
      run: make cover
    - name: Upload cover to codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/coverage.out
        name: code-coverage-${{ matrix.go-version }}
        token: ${{ secrets.CODECOV_TOKEN }}
